services:
  web:
    build:
      context: ../  # Build context is the parent folder
      dockerfile: ./docker/Dockerfile
    container_name: simple_node_app
    ports:
      - "3000:3000"
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=3000
